// Exports Foundry build artifacts as typed `as const` ABIs for wagmi/viem.
// Usage: (cd contracts && forge build) && node scripts/export-abis.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "frontend/src/contracts/abis");
mkdirSync(outDir, { recursive: true });

const contracts = ["MockUSDC", "ComputeOracle", "ComputeOption", "OptionFactory"];
const index = [];

for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(root, `contracts/out/${name}.sol/${name}.json`), "utf8"));
  const exportName = name.charAt(0).toLowerCase() + name.slice(1) + "Abi";
  writeFileSync(
    join(outDir, `${name}.ts`),
    `// Auto-generated by scripts/export-abis.mjs — do not edit.\nexport const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  index.push(`export { ${exportName} } from "./${name}";`);
  console.log(`exported ${name} (${artifact.abi.length} entries)`);
}
writeFileSync(join(outDir, "index.ts"), index.join("\n") + "\n");
