import { describe, expect, it } from "vitest";
import {
  calculateBreakEven,
  calculateCallPrice,
  calculateCappedOptionPrice,
  calculateDelta,
  calculateIntrinsicValue,
  calculatePutPrice,
  isStalePremium,
  normCdf,
  summarizeTrade,
} from "./optionsPricing";

// Test vectors from docs/handoff/08-DATA-AND-STATE.md (generated by the lead from this module on 2026-10-08).
const T30 = 30 / 365;
const T14 = 14 / 365;

describe("Black-Scholes model prices", () => {
  it("prices the seeded demo series", () => {
    expect(calculateCallPrice({ spot: 2, strike: 2.2, timeToExpiry: T30, volatility: 0.42 })).toBeCloseTo(0.032235, 6);
    expect(calculatePutPrice({ spot: 2, strike: 1.8, timeToExpiry: T30, volatility: 0.42 })).toBeCloseTo(0.022785, 6);
    expect(calculateCallPrice({ spot: 2, strike: 2, timeToExpiry: T14, volatility: 0.42 })).toBeCloseTo(0.067107, 6);
    expect(calculateCallPrice({ spot: 4, strike: 2.2, timeToExpiry: T30, volatility: 0.42 })).toBeCloseTo(1.807221, 6);
  });

  it("caps model value at the series payout cap", () => {
    expect(calculateCappedOptionPrice("CALL", { spot: 2, strike: 2.2, timeToExpiry: T30, volatility: 0.42 }, 2.2)).toBeCloseTo(0.032235, 6);
    expect(calculateCappedOptionPrice("CALL", { spot: 4, strike: 2.2, timeToExpiry: T30, volatility: 0.42 }, 2.2)).toBeCloseTo(1.742751, 6);
    expect(calculateCappedOptionPrice("PUT", { spot: 2, strike: 1.8, timeToExpiry: T30, volatility: 0.42 }, 1.8)).toBeCloseTo(0.022785, 6);
  });

  it("computes delta and the normal CDF", () => {
    expect(calculateDelta("CALL", { spot: 2, strike: 2.2, timeToExpiry: T30, volatility: 0.42 })).toBeCloseTo(0.240705, 6);
    expect(normCdf(0)).toBeCloseTo(0.5, 8); // 0.5000000005: the approximation error documented in the handoff
    expect(normCdf(1.96)).toBeCloseTo(0.975002, 6);
  });
});

describe("payoff maths", () => {
  it("intrinsic value respects the cap", () => {
    expect(calculateIntrinsicValue("CALL", 4, 2.2, 2.2)).toBeCloseTo(1.8, 9);
    expect(calculateIntrinsicValue("CALL", 9, 2.2, 2.2)).toBe(2.2);
    expect(calculateIntrinsicValue("PUT", 1.2, 1.8, 1.8)).toBeCloseTo(0.6, 9);
    expect(calculateIntrinsicValue("CALL", 2, 2.2, 2.2)).toBe(0);
  });

  it("break-even is strike ± premium", () => {
    expect(calculateBreakEven("CALL", 2.2, 0.035)).toBeCloseTo(2.235, 9);
    expect(calculateBreakEven("PUT", 1.8, 0.025)).toBeCloseTo(1.775, 9);
  });

  it("summarizes the demo trade: 10 × H100 CALL $2.20", () => {
    const s = summarizeTrade({ kind: "CALL", strike: 2.2, premium: 0.035, payoutCap: 2.2, contractSize: 100, contracts: 10 });
    expect(s.gpuHours).toBe(1000);
    expect(s.totalPremium).toBeCloseTo(35, 9);
    expect(s.maxLoss).toBeCloseTo(35, 9);
    expect(s.maxPayout).toBeCloseTo(2200, 9);
    expect(s.maxProfit).toBeCloseTo(2165, 9);
    expect(s.breakEven).toBeCloseTo(2.235, 9);
    expect(s.collateralBacking).toBeCloseTo(2200, 9);
  });
});

describe("stale premium detection", () => {
  it("flags a premium below the current exercise value", () => {
    expect(isStalePremium("CALL", 4, 2.2, 0.035, 2.2)).toBe(true); // pays 1.80 now, costs 0.035
    expect(isStalePremium("CALL", 2, 2.2, 0.035, 2.2)).toBe(false); // out of the money
    expect(isStalePremium("CALL", 2.22, 2.2, 0.035, 2.2)).toBe(false); // ITM by less than the premium
    expect(isStalePremium("PUT", 1.5, 1.8, 0.025, 1.8)).toBe(true);
  });
});
